import type { RoomType, Experience, FAQItem, GalleryImage, PageMeta } from './types';

export const rooms: RoomType[] = [
  {
    id: 'evolution',
    slug: 'evolution',
    code: 'R-01',
    name: 'The Evolution Room',
    concept: 'A queen suite inspired by adaptation — the quiet mechanism of change.',
    description: 'A cozy queen suite at Wetrock, blending science, stargazing, and spring-fed tranquility.',
    story: 'Evolution is not sudden. It is the accumulation of small, persistent changes over deep time. This room sits at the edge of the spring path, where water has slowly reshaped stone. The interior mirrors that patience — warm wood, layered textures, a window frame that catches first light over the red-rock terrace. Sleep here and you sleep inside the idea that everything around you is still becoming something else.',
    image: 'https://images.pexels.com/photos/7163597/pexels-photo-7163597.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/7163597/pexels-photo-7163597.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/12513475/pexels-photo-12513475.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30708770/pexels-photo-30708770.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    sleeps: 2,
    bed: 'Queen',
    baths: 1,
    rateFrom: 184,
    size: '320 sq ft',
    view: 'Spring path and terraced earthworks',
    amenities: ['Private bathroom', 'Air conditioning', 'Continental breakfast', 'Wi-Fi', 'Camp spot included', 'Pet friendly'],
    features: [
      { label: 'Bed', value: 'Queen' },
      { label: 'Bath', value: 'Private' },
      { label: 'Sleeps', value: '2 guests' },
      { label: 'Includes', value: 'Camp spot' },
    ],
    category: 'room',
  },
  {
    id: 'big-bang',
    slug: 'big-bang',
    code: 'R-02',
    name: 'The Big Bang Suite',
    concept: 'Where it all began — a king suite oriented toward the darkest sky.',
    description: 'A spacious king suite with a private balcony and a window framed for pre-dawn stargazing.',
    story: 'Thirteen point eight billion years ago, everything expanded from a single, impossibly dense point. This suite is the property\'s expansion — the largest room, oriented so that the balcony catches the clearest dark-sky corridor. The ceiling is painted deep obsidian with subtle constellation mapping. Lie back and you are looking up into the same sky that the first light ever traveled through.',
    image: 'https://images.pexels.com/photos/12513475/pexels-photo-12513475.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/12513475/pexels-photo-12513475.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7746470/pexels-photo-7746470.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/4337448/pexels-photo-4337448.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    sleeps: 2,
    bed: 'King',
    baths: 1,
    rateFrom: 289,
    size: '480 sq ft',
    view: 'Dark-sky corridor and La Sal Mountains',
    amenities: ['Private balcony', 'King bed', 'Air conditioning', 'Continental breakfast', 'Wi-Fi', 'Stone fireplace', 'Pet friendly'],
    features: [
      { label: 'Bed', value: 'King' },
      { label: 'Bath', value: 'Private' },
      { label: 'Sleeps', value: '2 guests' },
      { label: 'Feature', value: 'Private balcony' },
    ],
    category: 'room',
  },
  {
    id: 'cosmos',
    slug: 'cosmos',
    code: 'R-03',
    name: 'The Cosmos Suite',
    concept: 'Two bedrooms, two baths — a guesthouse scaled for a small crew of explorers.',
    description: 'A two-bedroom, two-bathroom guesthouse with swimming pool access, jacuzzi, and science-themed interiors.',
    story: 'Cosmos means order. The Cosmos Suite is the property\'s most structured space — two bedrooms, two full baths, and a shared living area that opens onto the pool deck. Designed for a family or a small group who want to spread out without losing each other. Every room references a different scale of the universe, from the cellular to the galactic.',
    image: 'https://images.pexels.com/photos/7746470/pexels-photo-7746470.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/7746470/pexels-photo-7746470.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/26859040/pexels-photo-26859040.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7163597/pexels-photo-7163597.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    sleeps: 4,
    bed: '2 Queen',
    baths: 2,
    rateFrom: 322,
    size: '720 sq ft',
    view: 'Pool, gardens, and red-rock horizon',
    amenities: ['Two bedrooms', 'Two bathrooms', 'Pool access', 'Jacuzzi', 'Air conditioning', 'Continental breakfast', 'Wi-Fi', 'Fitness center', 'Pet friendly'],
    features: [
      { label: 'Bed', value: '2 Queen' },
      { label: 'Bath', value: '2 Private' },
      { label: 'Sleeps', value: '4 guests' },
      { label: 'Access', value: 'Pool & jacuzzi' },
    ],
    category: 'room',
  },
  {
    id: 'deep-time',
    slug: 'deep-time',
    code: 'R-04',
    name: 'The Deep Time Room',
    concept: 'A queen suite with a stone fireplace and a view into geological patience.',
    description: 'A warm, rustic queen suite with a stone fireplace, overlooking the concentric terracing of the property.',
    story: 'Deep time is the idea that the earth we see is the result of processes too slow for a human lifetime to measure. This room faces the property\'s most striking feature — the concentric, semi-circular terracing carved into the reddish-brown soil. The stone fireplace is local sandstone, laid by hand. The window is a frame for a landscape that is still, imperceptibly, being shaped.',
    image: 'https://images.pexels.com/photos/30708770/pexels-photo-30708770.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/30708770/pexels-photo-30708770.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8951846/pexels-photo-8951846.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/4337448/pexels-photo-4337448.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    sleeps: 2,
    bed: 'Queen',
    baths: 1,
    rateFrom: 247,
    size: '360 sq ft',
    view: 'Concentric terracing and spring gardens',
    amenities: ['Stone fireplace', 'Private bathroom', 'Air conditioning', 'Continental breakfast', 'Wi-Fi', 'Garden access', 'Pet friendly'],
    features: [
      { label: 'Bed', value: 'Queen' },
      { label: 'Bath', value: 'Private' },
      { label: 'Sleeps', value: '2 guests' },
      { label: 'Feature', value: 'Stone fireplace' },
    ],
    category: 'room',
  },
  {
    id: 'camp-spot',
    slug: 'camp-spot',
    code: 'C-01',
    name: 'Dark Sky Camp Spot',
    concept: 'Sleep under the darkest sky in the continental United States.',
    description: 'A luxury camp spot on the property, included with select rooms or bookable on its own. Real beds, real comfort, unreal sky.',
    story: 'Moab sits beneath some of the darkest sky in the lower forty-eight. The camp spots at Wetrock are positioned along the solar-system walk, far enough from the main house that the only light is starlight. Each spot has a raised platform, a real mattress, and a canvas shelter. This is not roughing it — it is choosing to sleep where the sky is loudest.',
    image: 'https://images.pexels.com/photos/5717775/pexels-photo-5717775.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/5717775/pexels-photo-5717775.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/18717287/pexels-photo-18717287.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/17877136/pexels-photo-17877136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    sleeps: 2,
    bed: 'Real mattress on platform',
    baths: 0,
    rateFrom: 138,
    size: '120 sq ft platform',
    view: 'Unobstructed 360-degree sky',
    amenities: ['Raised platform', 'Real mattress', 'Canvas shelter', 'Lantern', 'Access to house bathroom', 'Camp fire pit', 'Stargazing pad'],
    features: [
      { label: 'Sleeps', value: '2 guests' },
      { label: 'Bed', value: 'Platform mattress' },
      { label: 'Bath', value: 'House access' },
      { label: 'Sky', value: 'Bortle 2' },
    ],
    category: 'camping',
  },
  {
    id: 'private-retreat',
    slug: 'private-retreat',
    code: 'PR-01',
    name: 'The Private Retreat',
    concept: 'Exclusive access to the entire 15-acre property. The king suite, the queen suite, two luxury tents, and all of Wetrock to yourself.',
    description: 'A private Wetrock oasis near Moab. King suite and queen suite, each with a private bathroom, plus two luxury camp spots. Exclusive access to the spring, the solar-system walk, and the grounds.',
    story: 'Sometimes the experiment requires isolation. The Private Retreat is the entire property, closed to other guests. You get the king suite and the queen suite — each with a private bathroom — and two luxury camp spots for anyone who wants to sleep outside. The spring, the solar-system walk, the terracing, the goat trail: all yours. This is Wetrock as a personal laboratory.',
    image: 'https://images.pexels.com/photos/16134466/pexels-photo-16134466.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/16134466/pexels-photo-16134466.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/9702070/pexels-photo-9702070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/5717775/pexels-photo-5717775.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    sleeps: 6,
    bed: 'King + Queen + 2 camp platforms',
    baths: 2,
    rateFrom: 439,
    size: '15 acres',
    view: 'Everything',
    amenities: ['King suite', 'Queen suite', '2 luxury camp spots', 'Exclusive property access', 'Spring access', 'Solar-system walk', 'Goat trail', 'Private parking', 'Continental breakfast', 'Pet friendly'],
    features: [
      { label: 'Sleeps', value: '6 guests' },
      { label: 'Suites', value: 'King + Queen' },
      { label: 'Camp', value: '2 luxury tents' },
      { label: 'Access', value: 'Entire property' },
    ],
    category: 'retreat',
  },
  {
    id: 'compound',
    slug: 'compound',
    code: 'CP-01',
    name: 'The Wetrock Compound',
    concept: 'The whole property for up to 18 guests. A double kitchen, multiple bedrooms, on-site vehicle storage, and a science exhibition space.',
    description: 'A spacious compound rental sleeping up to 18 guests with an open living area, fully-equipped double kitchen, multiple bedrooms, and on-site vehicle and gear storage.',
    story: 'The Compound is Wetrock at full scale — every room, every camp spot, every common space booked together for a group. The double kitchen can feed eighteen. The living area converts into a presentation space for science exhibitions, concerts, astronomy nights, weddings, and educational gatherings. On-site vehicle storage means you can base a whole expedition here. This is Wetrock as a field station.',
    image: 'https://images.pexels.com/photos/19039607/pexels-photo-19039607.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/19039607/pexels-photo-19039607.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7363295/pexels-photo-7363295.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8360524/pexels-photo-8360524.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    sleeps: 18,
    bed: 'Multiple configurations',
    baths: 4,
    rateFrom: 1200,
    size: '15 acres + all structures',
    view: 'Red-rock desert and La Sal Mountains',
    amenities: ['Sleeps up to 18', 'Double kitchen', 'Multiple bedrooms', 'On-site vehicle storage', 'Gear storage', 'Event space', 'Science exhibition area', 'Pool & jacuzzi', 'Continental breakfast', 'Pet friendly', 'Group check-in'],
    features: [
      { label: 'Sleeps', value: 'Up to 18' },
      { label: 'Kitchen', value: 'Double' },
      { label: 'Bedrooms', value: 'Multiple' },
      { label: 'Vehicle', value: 'On-site storage' },
    ],
    category: 'compound',
  },
];

export const experiences: Experience[] = [
  {
    id: 'spring',
    code: 'E-01',
    name: 'Spring Water Sanctuary',
    tagline: 'A spring-fed pond system you can walk through.',
    description: 'Wetrock sits on a natural spring. The water has been shaped into a series of connected ponds that wind through the property, supporting a micro-ecosystem of plants, insects, and birds. Walk the path and read the interpretive stations that explain the hydrology, the geology, and the biology of what you are seeing. This is not a garden. It is a living demonstration of how water moves through desert stone.',
    image: 'https://images.pexels.com/photos/1488087/pexels-photo-1488087.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    duration: 'Self-guided, 30-45 min',
    groupSize: 'All guests',
    price: 'Included with stay',
    season: 'Year-round',
    category: 'Self-guided',
  },
  {
    id: 'solar-system',
    code: 'E-02',
    name: 'Walk the Solar System',
    tagline: 'A scale model of the solar system laid out across 15 acres.',
    description: 'Wetrock\'s most distinctive feature is a walkable, to-scale model of the solar system. Each planet is placed at its correct relative distance from the sun, which sits at the center of the property. Walk from the sun to Neptune and you will have traveled the equivalent of 2.7 billion miles in a few hundred yards. The path is marked with interpretive stations that give you the real numbers — orbital periods, diameters, compositions. This is how distance feels.',
    image: 'https://images.pexels.com/photos/9503200/pexels-photo-9503200.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    duration: 'Self-guided, 20-30 min',
    groupSize: 'All guests',
    price: 'Included with stay',
    season: 'Year-round',
    category: 'Self-guided',
  },
  {
    id: 'goat-walk',
    code: 'E-03',
    name: 'Goat Walk & Picnic + Stargazing',
    tagline: 'Walk the goats through the desert, eat, then watch the sky open.',
    description: 'Wetrock keeps a small herd of goats. The goat walk takes you along the trail that loops the property and into the adjacent desert, with the goats as your companions. You will learn about the goats, the desert ecology they navigate, and the role of keystone species in maintaining ecosystems. The walk ends at a picnic spot with a prepared lunch. As the sun sets, the stargazing session begins — a guided tour of the night sky with a telescope and a resident astronomer.',
    image: 'https://images.pexels.com/photos/7509142/pexels-photo-7509142.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    duration: '4-5 hours',
    groupSize: 'Up to 8',
    price: '$120 per person',
    season: 'Mar-Nov',
    category: 'Guided',
  },
  {
    id: 'stargazing',
    code: 'E-04',
    name: 'Guided Stargazing',
    tagline: 'A telescope, a dark sky, and someone who knows what they are looking at.',
    description: 'Moab is a certified dark-sky community. Wetrock\'s location, set back from town lights with a clear horizon, makes it one of the best viewing spots in the area. The guided stargazing session uses an 8-inch Dobsonian telescope. You will see planets, nebulae, star clusters, and galaxies — and learn how to navigate the sky by eye. Sessions are weather-dependent and scheduled around the moon phase.',
    image: 'https://images.pexels.com/photos/13009055/pexels-photo-13009055.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    duration: '90 min',
    groupSize: 'Up to 12',
    price: '$65 per person',
    season: 'Year-round, weather permitting',
    category: 'Guided',
  },
  {
    id: 'stones',
    code: 'E-05',
    name: 'The Stones',
    tagline: 'A hands-on geology lab using the rocks under your feet.',
    description: 'The desert around Moab is a textbook of geological time — Entrada sandstone, Navajo sandstone, Kayenta formation, Morrison formation. The Stones is a hands-on session where you handle real specimens from each layer, learn to identify them, and then walk the property to find where they surface. You will leave understanding why Moab looks the way it does — not from a book, but from the rock itself.',
    image: 'https://images.pexels.com/photos/999073/pexels-photo-999073.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    duration: '2 hours',
    groupSize: 'Up to 10',
    price: '$45 per person',
    season: 'Year-round',
    category: 'Workshop',
  },
  {
    id: 'exhibitions',
    code: 'E-06',
    name: 'Science Exhibitions & Events',
    tagline: 'Concerts, astronomy nights, weddings, and educational gatherings.',
    description: 'Wetrock hosts a calendar of special events — concerts in the spring garden, astronomy nights with visiting scientists, wedding ceremonies on the terracing, and educational gatherings for schools and universities. The property converts into a venue. Check the calendar for upcoming events or inquire about hosting your own.',
    image: 'https://images.pexels.com/photos/8360524/pexels-photo-8360524.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    duration: 'Varies',
    groupSize: 'Up to 50',
    price: 'Varies by event',
    season: 'Year-round',
    category: 'Special',
  },
];

export const faqItems: FAQItem[] = [
  {
    id: 'f1',
    category: 'Stays',
    question: 'What time is check-in and check-out?',
    answer: 'Check-in is from 3:00 PM to 7:00 PM. Check-out is by 11:00 AM. If you need to arrive after 7 PM, let us know in advance and we will arrange a late check-in.',
  },
  {
    id: 'f2',
    category: 'Stays',
    question: 'Is breakfast included?',
    answer: 'Yes. A continental or American breakfast is included with every room booking. Breakfast is served in the main house dining area. For the compound and private retreat bookings, we can arrange expanded meal service.',
  },
  {
    id: 'f3',
    category: 'Stays',
    question: 'Are pets welcome?',
    answer: 'Yes. Wetrock is pet-friendly. There is no pet fee. We ask that pets be kept on leash in the garden and spring areas to protect the wildlife. The goat walk is not suitable for pets.',
  },
  {
    id: 'f4',
    category: 'Stays',
    question: 'What amenities does the property have?',
    answer: 'All guests have access to the seasonal heated saltwater pool, outdoor hot tub, oak barrel sauna, and the spring gardens. The main house has a shared living area with a stone fireplace. Wi-Fi is available throughout.',
  },
  {
    id: 'f5',
    category: 'Stargazing',
    question: 'What if it is cloudy on the night of my stargazing session?',
    answer: 'Stargazing sessions are weather-dependent. If the sky is not clear enough for a productive session, we will reschedule to the next available night of your stay or refund the session. We monitor forecasts and will make the call by 4 PM on the day of the session.',
  },
  {
    id: 'f6',
    category: 'Stargazing',
    question: 'Do I need any experience or equipment?',
    answer: 'No. The guided stargazing session is designed for beginners. We provide the telescope and all guidance. If you have your own binoculars or telescope, bring them — the dark sky here rewards every instrument.',
  },
  {
    id: 'f7',
    category: 'Stargazing',
    question: 'When is the best time of year for stargazing?',
    answer: 'Moab has clear skies most of the year. The best viewing is from September through May, when the air is dry and the Milky Way is visible. Summer nights are warm and comfortable but the sky is brighter due to the galactic core. We schedule around the moon phase — the week around the new moon is darkest.',
  },
  {
    id: 'f8',
    category: 'Booking',
    question: 'How does booking work?',
    answer: 'Select your dates, choose a room or experience, and submit a reservation request. We review every request personally and confirm within 24 hours. No payment is charged until your booking is confirmed. For groups and retreats, use the Groups & Retreats inquiry form.',
  },
  {
    id: 'f9',
    category: 'Booking',
    question: 'What is the cancellation policy?',
    answer: 'Free cancellation up to 14 days before check-in. Within 14 days, the first night is non-refundable. Within 48 hours, the full reservation is non-refundable. We will work with you on weather-related cancellations for stargazing-focused stays.',
  },
  {
    id: 'f10',
    category: 'Getting Here',
    question: 'How do I get to Wetrock?',
    answer: 'Wetrock is located at 1275 Boulder Ave, Moab, Utah — a short walk from downtown Moab, yet set back enough for dark skies. The closest airport is Canyonlands Field (CNY), 20 minutes away. Salt Lake City International (SLC) is 4 hours by car. Grand Junction, CO is 2 hours. Free private parking is available on-site.',
  },
  {
    id: 'f11',
    category: 'Getting Here',
    question: 'Do I need a car?',
    answer: 'Not necessarily. Downtown Moab is walkable from the property, and we can arrange shuttles to Arches and Canyonlands trailheads. However, a car gives you the most flexibility for exploring the region, especially Canyonlands and the La Sal Mountains.',
  },
  {
    id: 'f12',
    category: 'Groups',
    question: 'Can I host a wedding, retreat, or event at Wetrock?',
    answer: 'Yes. The Wetrock Compound can be booked for groups up to 18 overnight guests, and the property can host events for up to 50 people. We host weddings, corporate retreats, artist residencies, and educational gatherings. Visit the Groups & Retreats page or use the Contact page to inquire.',
  },
];

export const galleryImages: GalleryImage[] = [
  { id: 'g1', src: 'https://images.pexels.com/photos/9702070/pexels-photo-9702070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Red rock formations in Moab', category: 'Grounds', caption: 'The property boundary — Entrada sandstone at dawn' },
  { id: 'g2', src: 'https://images.pexels.com/photos/13009055/pexels-photo-13009055.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Milky Way over Utah desert', category: 'Sky', caption: 'The Milky Way from the stargazing pad — Bortle 2 sky' },
  { id: 'g3', src: 'https://images.pexels.com/photos/7163597/pexels-photo-7163597.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Cozy bedroom with stone wall', category: 'Rooms', caption: 'The Evolution Room — warm wood, layered textures' },
  { id: 'g4', src: 'https://images.pexels.com/photos/1488087/pexels-photo-1488087.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Desert water oasis', category: 'Spring', caption: 'The spring-fed pond system — a living hydrology lab' },
  { id: 'g5', src: 'https://images.pexels.com/photos/5717775/pexels-photo-5717775.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Glamping tents in Utah desert', category: 'Camping', caption: 'Dark sky camp spots along the solar-system walk' },
  { id: 'g6', src: 'https://images.pexels.com/photos/7746470/pexels-photo-7746470.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Stone fireplace in rustic lodge', category: 'Rooms', caption: 'The main house living area — local sandstone, laid by hand' },
  { id: 'g7', src: 'https://images.pexels.com/photos/9503200/pexels-photo-9503200.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Red rock formation', category: 'Grounds', caption: 'A planet station on the solar-system walk' },
  { id: 'g8', src: 'https://images.pexels.com/photos/11768608/pexels-photo-11768608.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Milky Way above observatory', category: 'Sky', caption: 'Guided session — 8-inch Dobsonian under the galactic core' },
  { id: 'g9', src: 'https://images.pexels.com/photos/7509142/pexels-photo-7509142.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Goat in rocky terrain', category: 'Experiences', caption: 'The goat walk — keystone species in motion' },
  { id: 'g10', src: 'https://images.pexels.com/photos/16134466/pexels-photo-16134466.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Moab desert landscape', category: 'Grounds', caption: 'The 15-acre property — concentric terracing visible at lower right' },
  { id: 'g11', src: 'https://images.pexels.com/photos/999073/pexels-photo-999073.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Balanced rock formation', category: 'Moab', caption: 'Balanced Rock, Arches National Park — 12 miles north' },
  { id: 'g12', src: 'https://images.pexels.com/photos/12427271/pexels-photo-12427271.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Canyonlands at sunset', category: 'Moab', caption: 'Canyonlands at sunset — 30 miles southwest' },
  { id: 'g13', src: 'https://images.pexels.com/photos/12513475/pexels-photo-12513475.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Rustic cabin bedroom', category: 'Rooms', caption: 'The Big Bang Suite — a window framed for pre-dawn sky' },
  { id: 'g14', src: 'https://images.pexels.com/photos/17877136/pexels-photo-17877136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Desert under starlit sky', category: 'Sky', caption: 'Camp spot view — the only light is starlight' },
  { id: 'g15', src: 'https://images.pexels.com/photos/21858663/pexels-photo-21858663.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Desert landscape under blue sky', category: 'Moab', caption: 'The Colorado Plateau — the living lab surrounding Wetrock' },
  { id: 'g16', src: 'https://images.pexels.com/photos/8360524/pexels-photo-8360524.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Campfire gathering at night', category: 'Experiences', caption: 'Evening gatherings — the property converts into a venue' },
];

export const pages: PageMeta[] = [
  { path: '/', label: 'Home', title: 'Wetrock', subtitle: 'A science-based environment in Moab, Utah', section: 'Start' },
  { path: '/stay', label: 'Stay', title: 'Accommodations', subtitle: 'A specimen catalog of places to sleep', section: 'Stay' },
  { path: '/stay/:slug', label: 'Room Detail', title: 'Room', subtitle: '', section: 'Stay' },
  { path: '/camping', label: 'Camping', title: 'Dark Sky Camping', subtitle: 'Sleep where the sky is loudest', section: 'Stay' },
  { path: '/private-retreat', label: 'Private Retreat', title: 'The Private Retreat', subtitle: 'The entire 15 acres, to yourself', section: 'Stay' },
  { path: '/compound', label: 'The Compound', title: 'The Wetrock Compound', subtitle: 'A field station for up to 18', section: 'Stay' },
  { path: '/stargazing', label: 'Stargazing', title: 'Stargazing', subtitle: 'One of the darkest skies in the lower 48', section: 'Experience' },
  { path: '/experiences', label: 'Experiences', title: 'Experiences', subtitle: 'Science you can walk through', section: 'Experience' },
  { path: '/discover-moab', label: 'Discover Moab', title: 'Discover Moab', subtitle: 'The living lab surrounding Wetrock', section: 'Destination' },
  { path: '/about', label: 'The Experiment', title: 'The Experiment', subtitle: 'Not themed hospitality. Physical science, made immersive.', section: 'About' },
  { path: '/kit-host', label: 'Kit / Host', title: 'Kit in Wetrock', subtitle: 'The host and the experiment', section: 'About' },
  { path: '/gallery', label: 'Gallery', title: 'Gallery', subtitle: 'A visual archive of the property', section: 'Destination' },
  { path: '/groups', label: 'Groups & Retreats', title: 'Groups & Retreats', subtitle: 'For retreats, residencies, weddings, and gatherings', section: 'Groups' },
  { path: '/location', label: 'Location', title: 'Location', subtitle: '1275 Boulder Ave, Moab, Utah', section: 'Destination' },
  { path: '/plan-your-stay', label: 'Plan Your Stay', title: 'Plan Your Stay', subtitle: 'Everything you need to decide', section: 'Plan' },
  { path: '/faq', label: 'FAQ', title: 'Frequently Asked Questions', subtitle: 'The specifics, answered', section: 'Plan' },
  { path: '/contact', label: 'Contact', title: 'Contact', subtitle: 'Reach the people behind the experiment', section: 'Plan' },
];

export const navLinks = [
  { path: '/stay', label: 'Stay' },
  { path: '/experiences', label: 'Experiences' },
  { path: '/stargazing', label: 'Stargazing' },
  { path: '/discover-moab', label: 'Discover Moab' },
  { path: '/about', label: 'The Experiment' },
  { path: '/plan-your-stay', label: 'Plan Your Stay' },
];
